name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Main Project
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: 'v5.5.3'
          target: esp32
          command: idf.py build


      - name: Build Test Project
        uses: espressif/esp-idf-ci-action@v1
        with:
          path: test
          esp_idf_version: 'v5.5.3'
          target: esp32
          command: idf.py build



      - name: Kconfig Check
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: 'v5.5.3'
          target: esp32
          command: find . -name "Kconfig*" | xargs -r python -m kconfcheck
